ERROR:routes:Exception on /summonerSearch [POST]
Traceback (most recent call last):
  File "/Users/bsawa/Documents/devenv/mTrack/M-Track/flask/routes.py", line 155, in summonerSearch
    if len(gameData) < 1:
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsawa/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bsawa/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bsawa/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bsawa/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/bsawa/Documents/devenv/mTrack/M-Track/flask/routes.py", line 159, in summonerSearch
    mtrack(riotID, riotIDPuuid, regionSelect, RIOTAPIKEY, 20)
  File "/Users/bsawa/Documents/devenv/mTrack/M-Track/mTrack/update.py", line 392, in mtrack
    uniqueGameIDs = findUniqueIDs(gameIDsFromDB, matchList)
  File "/Users/bsawa/Documents/devenv/mTrack/M-Track/mTrack/update.py", line 311, in findUniqueIDs
    set1 = set(list1)
TypeError: 'NoneType' object is not iterable
